Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -30,8 +30,7 @@ jobs:
       - name: Aqua code scanning(SCA, Sensitive data, IaC, SAST, pipeline file, initial SBOM)
         uses: docker://aquasec/aqua-scanner
         with:
-          args: trivy --version
-          #args: trivy fs --scanners misconfig,vuln,secret --sast --reachability .
+          args: trivy fs --scanners misconfig,vuln,secret --sast --reachability .
           # --file-patterns "conan-lock:conan*.ttlock" 
           # --format template --template "@Report-Templates/aqua.tpl" -o .github/workflows/code_scan_results.html
           # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
@@ -42,3 +41,33 @@ jobs:
           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
           GITHUB_TOKEN: ${{ github.token }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
+        
+  CI-Build:
+    needs: CI-Code
+    runs-on: ubuntu-22.04
+    steps:   
+    
+      - name: Checkout code
+        uses: actions/checkout@v2
+     
+      - name: SBOM Generation
+        run: |
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ github.token }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path conan.lock
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            ## --artifact-path "${{env.MY_APP_ROOT}}"
